spring:
  application:
    name: registry

  liquibase:
    change-log: classpath:/db/changelog/master.xml
  datasource:
    url: jdbc:mysql://localhost:3306/db_registry?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root

registry:
  account:
    default-status-create: ACTIVE

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  broker:
    exchange: ex.registry
    queue:
      account: queue.registry.account
      history-transaction: queue.registry.history-transaction
    routing:
      account: routing.registry.account
      history-transaction: routing.registry.history-transaction

logging:
  pattern:
    level: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %5p [%X{traceId},%X{spanId}] %c{1}:%L - %m%n"

management:
  tracing:
    enabled: true