spring:
  application:
    name: registry

  liquibase:
    change-log: classpath:/db/changelog/master.xml
  datasource:
    url: jdbc:mysql://localhost:3306/db_registry?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root

registry:
  account:
    default-status-create: ACTIVE

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  broker:
    exchange: ex.registry
    queue:
      account: queue.registry.account
    routing:
      account: routing.registry.account
